### ISSUE TITLE
Question: selected advanceControls in callback

### ISSUE THREAD

**Issue by rubybrowncoat** [cadin/panels#12]
In the context of panels used as a cutscene manager, is there a way to use multiple advance controls without giving each a target sequence and instead receive the selected control in the cutscene callback?

**Comment by cadin** [comment]
No, there isn't.
It would probably be pretty easy to send back the `target` for the selected button. Would that work for you?

**Comment by rubybrowncoat** [comment]
Yes, anything to distinguish between the available options would work fine.

**Comment by cadin** [comment]
This should work now if you pull the latest (v1.5).

You can set up `advanceControls` with `target` properties. Since these won't actually be triggering another sequence, you can set them to strings instead of integers if you want:

```lua
advanceControls = {
    { input = Panels.Input.A, target = 1 }, 
    { input = Panels.Input.B, target = "B" } 
},
```

Then you can accept the `target` of the chosen input in your game's cutscene callback:

```lua
function cutsceneDidFinish(target)
    print("User chose option: " .. target)
    -- etc...
end
```

I added a full example in Scene 6 of the [Cutscene example project](https://github.com/cadin/panels-cutscene-example).
