### ISSUE TITLE
Add options for advancing in a non-linear way

### ISSUE THREAD

**Issue by Verdi** [cadin/panels#5]
I would love to be able to create a choose your own adventure style comic/game with panels. I imagine there could be two different types of controls. A dialog chooser - A or B - and a spatial navigation - up, down, left, or right on the D-pad.

Dialog: this could work like being able to say that the A button advances to the next sequence but that the B button goes to a different, specified sequence. 

Spatial: another possibility might be using the four directions of the D-pad where the default direction advances to the next sequence like normal but you could define up, down, and left to go to different, named sequences.

**Comment by tgb20** [comment]
I think that the easiest way to create an implementation with the current codebase would be to extend the `advanceControl` to take in more than one option with a scene number for each option. The choice explanation can be handled in content.

**Comment by cadin** [comment]
@tgb20 Yeah, that sounds like a good way to do it. The rest of the code assumes a linear progression, so I'll have to unwind some of those bits first. I probably have time to look at this in the next couple of weeks.

**Comment by cadin** [comment]
I made some changes to enable this on the [nonlinear-story branch](https://github.com/cadin/panels/tree/nonlinear-story).

There are some simple examples in [this example project](https://github.com/cadin/panels-nonlinear-example) that show how it works. But basically, you can define multiple options in a sequence's `advanceControls` table. Those controls can target any sequence in your comic.

As mentioned above, it's mostly up to you to define how the controls are presented and explained. But I did include a few different examples for how you could do that, including a directional D-pad one, which could be pretty fun.

If y'all have some time to check this out I'd appreciate any feedback. Otherwise I'll work on the documentation and then merge into `main` in the next week or so.

**Comment by Verdi** [comment]
Thanks @cadin! I'm working through your tutorial now. I'll let you know how it goes.

**Comment by cadin** [comment]
I merged this change into `main`.

There's a dedicated page in the docs that explains how this should work:  
[Creating Comics with Branching Storylines](https://cadin.github.io/panels/docs/nonlinear-comics.html)

Let me know if you run into problems. I'm closing this, but you can reopen or just comment here if you have feedback.

Thanks!
